require('./users')
require('./departments')
require('./devices')
require('./medias')
require('./playlists')
require('./channels')
require('./template')
require('./schedulers')
require('./logrequests')
require('./assignplaylists')
require('./groups')
require('./slides')
require('./styles')

